spring:
  application:
    name: LifeTrackr

  datasource:
    url: jdbc:mysql://localhost:3306/lifetracker
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler

jwt:
  secret: YTNCaGNtRnBiZ1p2YkdGdWFtRnNjMkZ5WldGeWFXWnJaWEl1YzJWamRHbHZibk09
  expire-hours: 12
